### ISSUE TITLE
Warning on meteor 1.3

### ISSUE THREAD

**Issue by rioadrian** [sdomagala/fancybox#1]
Hi, I use sinda fancybox and have this warning message after I update meteor to 1.3

`autoprefixer: /Users/app/packages/sinda_fancybox/fancyBox/helpers/jquery.fancybox-buttons.css:34:2: Gradient has outdated direction syntax. New syntax is like`to left`instead of`right`.`   

Please fix this issue.
Thanks & Regards
Rio Adrian

**Comment by sdomagala** [comment]
Hello,
please check if https://github.com/sdomagala/fancybox/commit/6bb1abb5a12479781955e4963ffc386fab34bf36 solved the issue, reopen if it didn't

Cheers,
Sebastian

**Comment by rioadrian** [comment]
thanks @sdomagala for your quick response 👍

**Comment by rioadrian** [comment]
Hello,
I'm sorry, but can you merge this bugfix into atmosphere. 
thanks & regards
Rio

**Comment by sdomagala** [comment]
Hey @rioadrian,
pushed newest version to atmosphere.
Please let me know if it works as expected, there were few changes in API and I'm not using this library anymore to check

Thanks

**Comment by rioadrian** [comment]
Hi @sdomagala, it works as expected thank you very much.

Rio
